--================================================================================--
--================= GROUP 5: SQL ANALYTICAL QUERIES AND VIEWS ====================--
--================================================================================--

/*
 * QUERY 1: Net Profit Per Location
 * -------------------------------------------------
 * Calculates the estimated net profit generated by each operational store location
 * from its opening date up to the current date. This provides granular profitability
 * analysis crucial for evaluating individual store performance, justifying expansion,
 * and satisfying investor reporting requirements.
 */

-- CREATE VIEW -- 
DROP VIEW IF EXISTS location_profitability_since_opening;
CREATE OR REPLACE VIEW location_profitability_since_opening AS

WITH ReportEndDate AS (
    SELECT CURRENT_DATE AS period_end_date_inclusive
),

LocationInfo AS (
    SELECT
        location_id,
        location_name,
        opened_date AS period_start_date
    FROM locations
),

OperationalLocations AS (
    SELECT
        li.location_id,
        li.location_name,
        li.period_start_date,
        re.period_end_date_inclusive
    FROM LocationInfo li
    CROSS JOIN ReportEndDate re
    WHERE li.period_start_date <= re.period_end_date_inclusive
),

Revenue AS (
    SELECT
        ol.location_id,
        COALESCE(SUM(sod.quantity * sod.unit_price * (1 - COALESCE(sod.discount, 0) / 100.0)), 0.00) AS total_revenue
    FROM OperationalLocations ol
    LEFT JOIN sales_orders so ON ol.location_id = so.location_id
    LEFT JOIN sales_orders_details sod ON so.sales_orders_id = sod.sales_orders_id
    WHERE so.order_date BETWEEN ol.period_start_date AND ol.period_end_date_inclusive
    GROUP BY ol.location_id
),

ReturnsValue AS (
    SELECT
        ol.location_id,
        COALESCE(SUM(r.quantity_returned * (sod.unit_price * (1 - COALESCE(sod.discount, 0) / 100.0))), 0.00) AS total_return_value
    FROM OperationalLocations ol
    LEFT JOIN sales_orders so ON ol.location_id = so.location_id
    LEFT JOIN sales_orders_details sod ON so.sales_orders_id = sod.sales_orders_id
    JOIN returns r ON sod.sales_orders_detail_id = r.sales_orders_detail_id
    WHERE so.order_date BETWEEN ol.period_start_date AND ol.period_end_date_inclusive
    GROUP BY ol.location_id
),

COGS AS (
    SELECT
        ol.location_id,
        COALESCE(SUM(pod.quantity * pod.unit_cost), 0.00) AS total_cogs
    FROM OperationalLocations ol
    LEFT JOIN purchase_orders po ON ol.location_id = po.location_id
    LEFT JOIN purchase_order_details pod ON po.purchase_order_id = pod.purchase_order_id
    WHERE po.status = 'Received'
      AND po.delivery_date BETWEEN ol.period_start_date AND ol.period_end_date_inclusive
    GROUP BY ol.location_id
),

SalaryCost AS (
    SELECT
        ol.location_id,
        COALESCE(SUM(
            (e.yearly_salary / 12.0) *
            GREATEST(0,
                (DATE_PART('year', ol.period_end_date_inclusive) - DATE_PART('year', GREATEST(e.hire_date, ol.period_start_date))) * 12 +
                (DATE_PART('month', ol.period_end_date_inclusive) - DATE_PART('month', GREATEST(e.hire_date, ol.period_start_date))) + 1
            )
        ), 0.00) AS total_estimated_salary_cost
    FROM OperationalLocations ol
    JOIN employees e ON ol.location_id = e.location_id
    WHERE e.hire_date IS NOT NULL
      AND e.yearly_salary IS NOT NULL
      AND e.hire_date <= ol.period_end_date_inclusive
      AND GREATEST(e.hire_date, ol.period_start_date) <= ol.period_end_date_inclusive
    GROUP BY ol.location_id
),

OtherExpenses AS (
    SELECT
        ol.location_id,
        COALESCE(SUM(ex.amount), 0.00) AS total_other_expenses
    FROM OperationalLocations ol
    LEFT JOIN expenses ex ON ol.location_id = ex.location_id
    WHERE ex.expense_date BETWEEN ol.period_start_date AND ol.period_end_date_inclusive
    GROUP BY ol.location_id
)

SELECT
    ol.location_name,
    ol.period_start_date,
    ol.period_end_date_inclusive AS report_end_date,
    ROUND(COALESCE(r.total_revenue, 0.00)::NUMERIC, 2) AS total_revenue,
    ROUND(COALESCE(rv.total_return_value, 0.00)::NUMERIC, 2) AS total_return_value,
    -- Net Revenue
    ROUND((COALESCE(r.total_revenue, 0.00) - COALESCE(rv.total_return_value, 0.00))::NUMERIC, 2) AS net_revenue,
    ROUND(COALESCE(c.total_cogs, 0.00)::NUMERIC, 2) AS total_cogs,
    -- Gross Profit
    ROUND((COALESCE(r.total_revenue, 0.00) - COALESCE(rv.total_return_value, 0.00) - COALESCE(c.total_cogs, 0.00))::NUMERIC, 2) AS gross_profit,
    ROUND(COALESCE(sc.total_estimated_salary_cost, 0.00)::NUMERIC, 2) AS total_estimated_salary_cost,
    ROUND(COALESCE(oe.total_other_expenses, 0.00)::NUMERIC, 2) AS total_other_expenses,
    -- Net Profit
    ROUND((
        (COALESCE(r.total_revenue, 0.00) - COALESCE(rv.total_return_value, 0.00) - COALESCE(c.total_cogs, 0.00))
        - COALESCE(sc.total_estimated_salary_cost, 0.00)
        - COALESCE(oe.total_other_expenses, 0.00)
    )::NUMERIC, 2) AS net_profit

FROM OperationalLocations ol
LEFT JOIN Revenue r ON ol.location_id = r.location_id
LEFT JOIN ReturnsValue rv ON ol.location_id = rv.location_id
LEFT JOIN COGS c ON ol.location_id = c.location_id
LEFT JOIN SalaryCost sc ON ol.location_id = sc.location_id
LEFT JOIN OtherExpenses oe ON ol.location_id = oe.location_id;

-- QUERY START -- 
SELECT *
FROM location_profitability_since_opening
-- Can customize what year to start, which location to see, etc. -- 
-- END -- 

-------------------------------------------------------------------------------

/*
 * QUERY 2: Monthly Gross Margin Per Location
 * ---------------------------------------------
 * Tracks gross margins over time to detect emerging financial trends or necessary
 * adjustments to inventory and products.
 * Created a VIEW for management to constantly check trends.
 */

-- CREATE VIEW -- 
DROP VIEW IF EXISTS monthly_location_gp;
CREATE OR REPLACE VIEW monthly_location_gp AS

WITH MonthlySales AS (
    SELECT
        l.location_id,
        l.location_name,
        DATE_TRUNC('month', so.order_date)::date AS sale_month,
        COALESCE(SUM(sod.quantity * sod.unit_price * (1 - COALESCE(sod.discount, 0) / 100.0)), 0.00) AS monthly_gross_revenue,
        COALESCE(SUM(r.quantity_returned * sod.unit_price * (1 - COALESCE(sod.discount, 0) / 100.0)) FILTER (WHERE r.return_id IS NOT NULL), 0.00) AS monthly_return_value
    FROM locations l
    LEFT JOIN sales_orders so ON l.location_id = so.location_id
    LEFT JOIN sales_orders_details sod ON so.sales_orders_id = sod.sales_orders_id 
    LEFT JOIN returns r ON sod.sales_orders_detail_id = r.sales_orders_detail_id
    GROUP BY l.location_id, l.location_name, DATE_TRUNC('month', so.order_date)
),

MonthlyCOGS AS (
    SELECT
        l.location_id,
        l.location_name,
        DATE_TRUNC('month', po.delivery_date)::date AS received_month,
        COALESCE(SUM(pod.quantity * pod.unit_cost), 0.00) AS monthly_cogs
    FROM locations l
    LEFT JOIN purchase_orders po ON l.location_id = po.location_id
    LEFT JOIN purchase_order_details pod ON po.purchase_order_id = pod.purchase_order_id
    WHERE po.status = 'Received'
      AND po.delivery_date IS NOT NULL
    GROUP BY l.location_id, l.location_name, DATE_TRUNC('month', po.delivery_date)
),

AllLocationMonths AS (
    SELECT location_id, location_name, sale_month AS report_month FROM MonthlySales
    UNION
    SELECT location_id, location_name, received_month AS report_month FROM MonthlyCOGS
),

MonthlyNetRevenue AS (
    SELECT
        location_id,
        location_name,
        sale_month,
        (monthly_gross_revenue - monthly_return_value) AS monthly_net_revenue
    FROM MonthlySales
)

SELECT
    alm.location_name,
    alm.report_month,
    ROUND(COALESCE(ms.monthly_gross_revenue, 0.00)::NUMERIC, 2) AS monthly_gross_revenue,
    ROUND(COALESCE(ms.monthly_return_value, 0.00)::NUMERIC, 2) AS monthly_return_value,
    ROUND(COALESCE(mnr.monthly_net_revenue, 0.00)::NUMERIC, 2) AS monthly_net_revenue,
    ROUND(COALESCE(mc.monthly_cogs, 0.00)::NUMERIC, 2) AS monthly_cogs,
    -- Monthly Gross Profit = Net Revenue - COGS
    ROUND((
        COALESCE(mnr.monthly_net_revenue, 0.00) - COALESCE(mc.monthly_cogs, 0.00)
    )::NUMERIC, 2) AS monthly_gross_profit,
    -- Monthly Gross Profit Margin (%)
    CASE
        WHEN COALESCE(mnr.monthly_net_revenue, 0.00) <= 0 THEN 0.00
        ELSE ROUND(
            ( (COALESCE(mnr.monthly_net_revenue, 0.00) - COALESCE(mc.monthly_cogs, 0.00)) / mnr.monthly_net_revenue ) * 100.0
        , 2)
    END AS monthly_gross_profit_margin
FROM AllLocationMonths alm
LEFT JOIN MonthlyNetRevenue mnr ON alm.location_id = mnr.location_id AND alm.report_month = mnr.sale_month
LEFT JOIN MonthlySales ms ON alm.location_id = ms.location_id AND alm.report_month = ms.sale_month
LEFT JOIN MonthlyCOGS mc ON alm.location_id = mc.location_id AND alm.report_month = mc.received_month;

-- QUERY START -- 
SELECT
    location_name,
    report_month,
    monthly_gross_revenue,
    monthly_return_value,
    monthly_net_revenue,
    monthly_cogs,
    monthly_gross_profit,
    monthly_gross_profit_margin 
FROM monthly_location_gp
-- Filters can be added like: WHERE location_name = 'ABC Queens East' AND report_month = '2025-02-01';
ORDER BY location_name, report_month;
-- END -- 

-------------------------------------------------------------------------------

/*
 * QUERY 3: COGS Breakdown By Product Category
 * -----------------------------------------
 * Highlights the categories with the highest cost burdens peer granularity required.
 * Current code written to calculate by month, but can always changed for yearly sums.
 */

-- QUERY START --
WITH PurchaseDetailCost AS (
    SELECT
        pod.purchase_order_detail_id,
        p.category,
        po.location_id,
        po.delivery_date,
        DATE_TRUNC('month', po.delivery_date)::date AS delivery_month,
        (pod.quantity * pod.unit_cost) AS line_cogs
    FROM purchase_order_details pod
    JOIN purchase_orders po ON pod.purchase_order_id = po.purchase_order_id
    JOIN products p ON pod.product_id = p.product_id
    WHERE po.status = 'Received'
        -- Optional: add location/date filters here when needed
        -- AND po.location_id = {location_id}
        -- AND po.delivery_date BETWEEN {start_date} AND {end_date}
)

SELECT
    pdc.delivery_month,
    pdc.category,
    ROUND(SUM(pdc.line_cogs)::NUMERIC, 2) AS total_cogs
FROM PurchaseDetailCost pdc
GROUP BY pdc.delivery_month, pdc.category
ORDER BY pdc.delivery_month, total_cogs DESC;
-- END --

-------------------------------------------------------------------------------

/*
 * QUERY 4: Estimated Labor Costs as a % of Net Revenue
 * ----------------------------------------------------
 * Provides a new efficiency metric that compares the estimated salary costs
 * to the net revenue per location. This will help determine whether each location
 * is operating on a lean model, or requires staffing changes between employees.
 */

-- QUERY START --

WITH parameters AS (
    SELECT
        DATE '2024-03-01' AS start_date,
        DATE '2025-04-25' AS end_date
		-- Change date parameters as needed, right now it's Lifetime Calculation)
),

RevenueNet AS (
    SELECT
        l.location_id,
        l.location_name,
        COALESCE(SUM(
            sod.quantity * sod.unit_price * (1 - COALESCE(sod.discount, 0) / 100.0)
        ), 0.00) AS total_gross_revenue,
        COALESCE(SUM(
            r.quantity_returned * sod.unit_price * (1 - COALESCE(sod.discount, 0) / 100.0)
        ), 0.00) AS total_return_value
    FROM locations l
    LEFT JOIN sales_orders so ON l.location_id = so.location_id
    LEFT JOIN sales_orders_details sod ON so.sales_orders_id = sod.sales_orders_id
    LEFT JOIN returns r ON sod.sales_orders_detail_id = r.sales_orders_detail_id
    CROSS JOIN parameters p
    WHERE so.order_date BETWEEN p.start_date AND p.end_date
    GROUP BY l.location_id, l.location_name
),

LaborCost AS (
    -- Estimate yearly salary cost for 1 year (no prorating here, assuming full year employment)
    SELECT
        e.location_id,
        COALESCE(SUM(e.yearly_salary), 0.00) AS total_estimated_salary_for_year
    FROM employees e
    WHERE e.hire_date IS NOT NULL
        AND e.yearly_salary IS NOT NULL
        AND e.hire_date <= (SELECT end_date FROM parameters) -- hired before year end
    GROUP BY e.location_id
)
SELECT
    rn.location_name,
    ROUND((COALESCE(rn.total_gross_revenue, 0.00) - COALESCE(rn.total_return_value, 0.00))::NUMERIC, 2) AS net_revenue,
    ROUND(lc.total_estimated_salary_for_year::NUMERIC, 2) AS total_estimated_salary,
    CASE
        WHEN (COALESCE(rn.total_gross_revenue, 0.00) - COALESCE(rn.total_return_value, 0.00)) = 0 THEN NULL
        ELSE ROUND(
            (lc.total_estimated_salary_for_year::NUMERIC / (rn.total_gross_revenue - rn.total_return_value)) * 100.0,
            2
        )
    END AS labor_cost_as_percentage_of_net_revenue
FROM RevenueNet rn
LEFT JOIN LaborCost lc ON rn.location_id = lc.location_id
ORDER BY labor_cost_as_percentage_of_net_revenue DESC NULLS LAST;
-- END --

-------------------------------------------------------------------------------

/*
 * QUERY 5: Top Products by Net Revenue
 * --------------------------------------
 * Identifies high-performing products by calculating their total net revenue,
 * which is the gross revenue generated from sales minus the value lost due to
 * returns and discounts. This helps prioritize inventory, marketing, and shelf space.
 */

-- QUERY START -- 
-- Common Table Expression (CTE) to calculate net revenue per sale detail line --
WITH SaleDetailNetValue AS (
    SELECT
        sod.sales_orders_detail_id,
        sod.product_id,
        (sod.quantity * sod.unit_price * (1 - COALESCE(sod.discount, 0) / 100.0)) AS gross_line_value,
        COALESCE(r.quantity_returned, 0) * (sod.unit_price * (1 - COALESCE(sod.discount, 0) / 100.0)) AS return_value_deduction,
        so.order_date
    FROM sales_orders_details sod
    JOIN sales_orders so ON sod.sales_orders_id = so.sales_orders_id
    LEFT JOIN returns r ON sod.sales_orders_detail_id = r.sales_orders_detail_id
)

SELECT
    p.category,
    ROUND(COALESCE(SUM(sdnv.gross_line_value - sdnv.return_value_deduction), 0.00)::NUMERIC, 2) AS total_net_revenue
FROM products p
JOIN SaleDetailNetValue sdnv ON p.product_id = sdnv.product_id
WHERE sdnv.order_date >= (CURRENT_DATE - INTERVAL '12 months') -- Checking for the last 12 months, can filter dates here
GROUP BY p.category
ORDER BY total_net_revenue DESC;
-- END --

-------------------------------------------------------------------------------

/*
 * QUERY 6: Sales Contribution by Loyalty Status & Category
 * ---------------------------------------------------------
 * Determines the contribution to sales (both transaction count and net revenue)
 * from registered loyalty members versus non-member (guest) checkouts, broken
 * down by product category. This helps assess the loyalty program's engagement
 * and value across different product segments. The query classifies members as
 * 'Loyalty Member', 'Registered Customer' or 'Guest'.
*/

-- QUERY START --
--- Common Table Expression (CTE) to calculate net value per detail line and classify customer type --
WITH SalesDetailClassification AS (
    SELECT
        CASE
            WHEN c.loyalty_member THEN 'Loyalty Member'
            WHEN c.loyalty_member IS FALSE THEN 'Registered Customer (Non-Loyalty)'
            ELSE 'Guest'
        END AS customer_type,
        (sod.quantity * sod.unit_price * (1 - COALESCE(sod.discount, 0) / 100.0))
        - (COALESCE(r.quantity_returned, 0) * (sod.unit_price * (1 - COALESCE(sod.discount, 0) / 100.0)))
        AS net_line_value
    FROM sales_orders so
    JOIN sales_orders_details sod ON so.sales_orders_id = sod.sales_orders_id
    LEFT JOIN returns r ON sod.sales_orders_detail_id = r.sales_orders_detail_id
    LEFT JOIN customers c ON so.customer_id = c.customer_id -- LEFT JOIN not JOIN
    WHERE so.order_date BETWEEN DATE('2024-03-01') AND CURRENT_DATE
)

SELECT
    customer_type,
    ROUND(COALESCE(SUM(net_line_value), 0.00), 2) AS total_net_revenue,
    COUNT(*) AS transaction_count
FROM SalesDetailClassification
GROUP BY customer_type
ORDER BY customer_type;

-- END --

-------------------------------------------------------------------------------

/*
 * QUERY 7: Sales Volume Seasonality for Key Items
 * -----------------------------------------------
 * Analyzes season sales quantities for specific products to optimize inventory
 * decisions. The exemplary query takes 3 products: Vanilla Ice cream, olive oil,
 * and Diet Coke to see seasonal variations. List can always be complimented or
 * changed to see seasonality of other products.
 */

-- QUERY START --
WITH SalesData AS (
    SELECT
        p.product_name,
        so.order_date,
        DATE_TRUNC('month', so.order_date)::date AS sale_month,
        sod.quantity,
        (sod.quantity * sod.unit_price * (1 - COALESCE(sod.discount, 0) / 100.0)) AS line_revenue
    FROM products p
    JOIN sales_orders_details sod ON p.product_id = sod.product_id
    JOIN sales_orders so ON sod.sales_orders_id = so.sales_orders_id
    WHERE
        p.product_name IN (
            'Vanilla Ice Cream (1.5qt)',
            'Olive Oil (Extra Virgin, 1L)',
            'Diet Cola (12pk Cans)'
            -- Can add more products, or take out the WHERE clause for seasonality of all products
        )
)

SELECT
    product_name,   
    CASE
        WHEN EXTRACT(MONTH FROM sale_month) IN (12, 1, 2) THEN 'Winter'
        WHEN EXTRACT(MONTH FROM sale_month) IN (3, 4, 5) THEN 'Spring'
        WHEN EXTRACT(MONTH FROM sale_month) IN (6, 7, 8) THEN 'Summer'
        WHEN EXTRACT(MONTH FROM sale_month) IN (9, 10, 11) THEN 'Fall'
        ELSE 'Unknown'
    END AS season,
    SUM(quantity) AS total_quantity_sold,
    ROUND(SUM(line_revenue)::NUMERIC, 2) AS total_revenue

FROM SalesData
GROUP BY product_name, season
ORDER BY product_name, season;
-- END --

-------------------------------------------------------------------------------

/*
 * QUERY 8: Return Rate of Supplier Products
 * ---------------------------------------
 * Created a view to see total units, total value and return rate of products
 * for suppliers. The level of granularity can be controled by the view, with
 * the default being each product name by each supplier. The example query
 * shows the grouped supplier-level view that can be used to asses quality of
 * suppliers.
 */

-- CREATE VIEW --
DROP VIEW IF EXISTS return_rate_by_sup;
CREATE OR REPLACE VIEW return_rate_by_sup AS

WITH SalesAndReturns AS (
    SELECT
        s.supplier_name,
        p.product_name,
        sod.product_id,
        SUM(COALESCE(sod.quantity, 0)) AS total_units_sold,
        SUM(COALESCE(r.quantity_returned, 0)) AS total_units_returned,
        SUM(
            COALESCE(r.quantity_returned, 0) * (sod.unit_price * (1 - COALESCE(sod.discount, 0) / 100.0))
        ) AS total_return_value
    FROM sales_orders_details sod
    JOIN sales_orders so ON sod.sales_orders_id = so.sales_orders_id
    LEFT JOIN returns r ON sod.sales_orders_detail_id = r.sales_orders_detail_id
    JOIN products p ON sod.product_id = p.product_id
    JOIN suppliers s ON p.supplier_id = s.supplier_id
    GROUP BY s.supplier_name, p.product_name, sod.product_id
)

SELECT
    supplier_name,
    product_name,
    SUM(total_units_returned) AS total_units_returned,
    ROUND(SUM(total_return_value)::NUMERIC, 2) AS total_return_value,
    CASE
        WHEN SUM(total_units_sold) = 0 THEN 0.00
        ELSE ROUND((SUM(total_units_returned)::NUMERIC / SUM(total_units_sold)::NUMERIC) * 100.0, 2)
    END AS return_rate_percentage
FROM SalesAndReturns
GROUP BY supplier_name, product_name
ORDER BY supplier_name ASC, total_return_value DESC;

-- QUERY START (to see total units returned, total value and return rate of each supplier) -- 
SELECT
    -- Can add product_name if a more granular analysis is needed
    supplier_name,
    SUM(total_units_returned) AS total_units_returned,
    ROUND(SUM(total_return_value)::NUMERIC, 2) AS total_return_value,
    CASE
        WHEN SUM(total_units_sold) = 0 THEN 0.00
        ELSE ROUND((SUM(total_units_returned)::NUMERIC / SUM(total_units_sold)::NUMERIC) * 100.0, 2)
    END AS return_rate_percentage
FROM (
    SELECT
        supplier_name,
        product_name,
        total_units_returned,
        total_return_value,
        -- To reconstruct total_units_sold from return_rate_percentage
        CASE
            WHEN return_rate_percentage = 0 THEN total_units_returned
            ELSE (total_units_returned * 100.0) / return_rate_percentage
        END AS total_units_sold
    FROM return_rate_by_sup
) sub
GROUP BY supplier_name
ORDER BY total_return_value DESC;
-- END --

-------------------------------------------------------------------------------

/*
 * QUERY 9: Supplier Rating
 * ---------------------------------------
 * Calculates Supplier Rating out of 5 by combining Return Rate and On-Time Delivery Rate.
 * Lower return rates and higher on-time delivery rates improve the score.
 * Weights: 60% Return Rate importance, 40% On-Time Delivery importance.
 */

 -- CREATE VIEW (For supplier delivery rates) -- 
 DROP VIEW IF EXISTS supplier_delivery_rate;
CREATE OR REPLACE VIEW supplier_delivery_rate AS

WITH DeliveryStatus AS (
    SELECT
        s.supplier_name,
        po.purchase_order_id,
        d.delivery_date,
        d.expected_delivery_date,
        CASE
            WHEN d.delivery_date IS NOT NULL
                 AND d.expected_delivery_date IS NOT NULL
                 AND d.delivery_date <= d.expected_delivery_date THEN 1
            ELSE 0
        END AS is_on_time
    FROM purchase_orders po
    JOIN deliveries d ON po.purchase_order_id = d.purchase_order_id
    JOIN suppliers s ON po.supplier_id = s.supplier_id
    WHERE po.status = 'Received' -- Only look at completed/received purchase orders
)
SELECT
    supplier_name,
    COUNT(*) AS total_deliveries,
    SUM(is_on_time) AS total_on_time_deliveries,
    CASE
        WHEN COUNT(*) = 0 THEN 0.00
        ELSE ROUND((SUM(is_on_time)::NUMERIC / COUNT(*)::NUMERIC) * 100.0, 2)
    END AS on_time_delivery_rate_percentage
FROM DeliveryStatus
GROUP BY supplier_name
ORDER BY on_time_delivery_rate_percentage DESC;
-- END --

-- CREATE VIEW OF SUPPLIER RATINGS -- 
DROP VIEW IF EXISTS supplier_rating;
CREATE OR REPLACE VIEW supplier_rating AS

WITH ReturnRateSummary AS (
    SELECT
        supplier_name,
        -- Aggregate the supplier-level return rate (already computed)
        SUM(total_units_returned) AS total_units_returned,
        ROUND(SUM(total_return_value)::NUMERIC, 2) AS total_return_value,
        CASE
            WHEN SUM(total_units_sold) = 0 THEN 0.00
            ELSE ROUND((SUM(total_units_returned)::NUMERIC / SUM(total_units_sold)::NUMERIC) * 100.0, 2)
        END AS return_rate_percentage
    FROM (
        SELECT
            supplier_name,
            product_name,
            total_units_returned,
            total_return_value,
            CASE
                WHEN return_rate_percentage = 0 THEN total_units_returned
                ELSE (total_units_returned * 100.0) / return_rate_percentage
            END AS total_units_sold
        FROM return_rate_by_sup
    ) sub
    GROUP BY supplier_name
)

SELECT
    rr.supplier_name,
    rr.return_rate_percentage,
    sd.on_time_delivery_rate_percentage,   
    -- Supplier Rating Formula
    ROUND(
        (
            ((100 - rr.return_rate_percentage) * 0.6) +
            (sd.on_time_delivery_rate_percentage * 0.4)
        ) / 20
    , 2) AS supplier_rating
FROM ReturnRateSummary rr
JOIN supplier_delivery_rate sd
    ON rr.supplier_name = sd.supplier_name
ORDER BY supplier_rating DESC;

-- QUERY START --
SELECT supplier_name, supplier_rating
FROM supplier_rating;
-- END --

-------------------------------------------------------------------------------

/*
 * QUERY 10: Customer Repurchase Rate
 * ---------------------------------------
 * Calculates the Customer Repurchase Rate.
 * Identifies customers who made multiple purchases by comparing first purchase dates to later purchases.
 * Measures the percentage of customers who returned for additional purchases within the dataset.
 */

-- QUERY START --
WITH FirstPurchase AS (
    -- Find each customer's first purchase date per location
    SELECT
        so.customer_id,
        l.location_name,
        MIN(so.order_date) AS first_purchase_date
    FROM sales_orders so
    JOIN locations l ON so.location_id = l.location_id
    GROUP BY so.customer_id, l.location_name
),

RepeatCustomers AS (
    -- Identify customers who made at least one additional purchase after their first purchase (same location)
    SELECT
        so.customer_id,
        l.location_name
    FROM sales_orders so
    JOIN locations l ON so.location_id = l.location_id
    JOIN FirstPurchase fp ON so.customer_id = fp.customer_id AND l.location_name = fp.location_name
    WHERE so.order_date > fp.first_purchase_date
)

SELECT
    l.location_name,
    ROUND(
        (COUNT(DISTINCT rc.customer_id)::NUMERIC / COUNT(DISTINCT so.customer_id)::NUMERIC) * 100.0,
        2
    ) AS repurchase_rate
FROM sales_orders so
JOIN locations l ON so.location_id = l.location_id
LEFT JOIN RepeatCustomers rc ON so.customer_id = rc.customer_id AND l.location_name = rc.location_name
GROUP BY l.location_name
ORDER BY l.location_name;
-- END --

-------------------------------------------------------------------------------